### PR TITLE
[tests] group unit test files with unit source files

### PR DESCRIPTION
**Pull request by wgtdkp**
This PR

- groups unit test files with their source files
- has no logic changes
- addresses issue https://github.com/openthread/ot-commissioner/issues/55

### CODE REVIEW

**Comment by wgtdkp** [comment]
This is the first step of reaching better code coverage.

**Comment by jwhui** [comment]
@wgtdkp, please resolve conflicts.

**Comment by jwhui** [comment]
@wgtdkp, can you take a look at the Travis failure?

https://travis-ci.org/github/openthread/ot-commissioner/jobs/678005079

**Comment by wgtdkp** [comment]
@jwhui This seems to be a known ninja [issue](https://github.com/ninja-build/ninja/issues/1599) on Mac OS. How about I switch travis build to GNU make on Mac OS X?

**Comment by jwhui** [comment]
> @jwhui This seems to be a known ninja [issue](https://github.com/ninja-build/ninja/issues/1599) on Mac OS. How about I switch travis build to GNU make on Mac OS X?

I think GNU make is fine. Make sure to use the `-j` arg, since make does not default to parallel build.

**Comment by wgtdkp** [comment]
> I think GNU make is fine. Make sure to use the `-j` arg, since make does not default to parallel build.
Thanks for reminding! will do.

**Pull request merged**
