### PR TITLE
[swig] add the diagnostic apis into swig file

### PR DESCRIPTION
**Pull request by ZhangLe2016**
integrated diagnostic apis into ot-commissioner.jar

### CODE REVIEW

**Comment by wgtdkp** [comment]
Your PR is still in "draft" state, you sure it's ready for review?

**Comment by ZhangLe2016** [comment]
> Your PR is still in "draft" state, you sure it's ready for review?

I have changed the PR state to "open", could you please take a look at it? thanks

**Comment by wgtdkp** [comment]
There are unrecognized C++ vector<> types in the generated java code in `.build-xxx-xxx/src/java/io/openthread/commissioner/`:
SWIGTYPE_p_std_functionxxxxxxx.java.

You need to add:

```
%template(ChildIpv6AddrInfoVector) std::vector<ot::commissioner::ChildIpv6AddrInfo>;
%template(ChildTableEntryVector) std::vector<ot::commissioner::ChildTableEntry>;
%template(RouteDataEntryVector) std::vector<ot::commissioner::RouteDataEntry>;
```
together with the existing:
```
%template(ChannelMask) std::vector<ot::commissioner::ChannelMaskEntry>;
%template(StringVector) std::vector<std::string>;
```

**Comment by ZhangLe2016** [comment]
@jwhui, could you please review this PR for me? thanks~~

**Comment by ZhangLe2016** [comment]
@jwhui Could you please take a look at my code? I would be very grateful for your feedback.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
