### PR TITLE
[thci] change python format string to format function

### PR DESCRIPTION
**Pull request by canisLupus1313**
Change format string introduced in python 3 to python 2 compatible 'format' function.

### CODE REVIEW

**Comment by canisLupus1313** [comment]
@jwhui The CI failures seem to be unrelated to my changes. so Can You take a look at this PR?

**Review by edmont — APPROVED** [review]

**Comment by edmont** [comment]
@simonlingoogle would you mind taking a look here?

**Review by wgtdkp — APPROVED** [review]
@edmont This PR is failing with Android NDK tests, I created https://github.com/openthread/ot-commissioner/pull/233 to fix it.

Please rebase after https://github.com/openthread/ot-commissioner/pull/233 is merged so that @jwhui can merge you PR without CI break :)

**Comment by canisLupus1313** [comment]
@jwhui @wgtdkp Thanks for the help.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
